// baseline.test.ts — Task 4 (S-P14): the committed baseline is generated by the tool and
// pinned to a cut. Oracle (plan Task 4): the baseline file itself IS the fixture under test —
// a hand-authored or unpinned entry is a failed baseline, mechanically enforced here.
import { describe, expect, test } from 'bun:test';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import type { BaselineFile } from './model.ts';

const BASELINE_PATH = join(import.meta.dir, '../../../../../../docs/superpowers/evidence/2026-09-18-supervisor-baseline.json');

const EXPECTED_SESSION_IDS = ['6a8a8fe4-f716-43f2-936f-0da47662d9d9', 'ba6e93f0-72e4-4e08-9c64-03d7ea6fb917'];

const SHA256_HEX = /^[0-9a-f]{64}$/;

describe('the committed transcript baseline (docs/superpowers/evidence/2026-09-18-supervisor-baseline.json)', () => {
  test('the baseline file exists and parses as JSON', () => {
    expect(existsSync(BASELINE_PATH)).toBe(true);
    expect(() => JSON.parse(readFileSync(BASELINE_PATH, 'utf8'))).not.toThrow();
  });

  test('v is 1 and it carries exactly the two committed session ids', () => {
    const raw = readFileSync(BASELINE_PATH, 'utf8');
    const parsed = JSON.parse(raw) as BaselineFile;
    expect(parsed.v).toBe(1);
    const ids = parsed.sessions.map((s) => s.sessionId).sort();
    expect(ids).toEqual([...EXPECTED_SESSION_IDS].sort());
  });

  test('every entry is PINNED: a cut with a positive bytes, a positive lines, and a 64-hex sha256 (S-P14)', () => {
    const raw = readFileSync(BASELINE_PATH, 'utf8');
    const parsed = JSON.parse(raw) as BaselineFile;
    expect(parsed.sessions.length).toBeGreaterThan(0);
    for (const entry of parsed.sessions) {
      expect(entry.cut).toBeDefined();
      expect(entry.cut.bytes).toBeGreaterThan(0);
      expect(entry.cut.lines).toBeGreaterThan(0);
      expect(SHA256_HEX.test(entry.cut.sha256)).toBe(true);
    }
  });

  test('the privacy wall: the serialized file contains no message text, prompt text, or "content" field (card `## Measure first`)', () => {
    const raw = readFileSync(BASELINE_PATH, 'utf8');
    for (const forbidden of ['"content"', '"text"', '"prompt"']) {
      expect(raw.includes(forbidden)).toBe(false);
    }
  });
});
